### ISSUE TITLE
[Bug] configs.json not found when reproduce benchmark.

### ISSUE THREAD

**Issue by LeiWang1999** [Hzfengsy/asplos-tvm#2]
Hello siyuan, to reproduce the benchmark results, I got the following issue, seems like we should provide a shape config json file 

```bash
/workspace/v-leiwang3/asplos-tvm# python3 benchmark/op/tune_auto_tir.py -w GMM-1024 -bs 1 -n 1000
Traceback (most recent call last):
  File "benchmark/op/tune_auto_tir.py", line 21, in <module>
    from workloads_fp16 import create_te_workload_f16
  File "/workspace/v-leiwang3/asplos-tvm/benchmark/op/workloads_fp16.py", line 437, in <module>
    shape_configs = load_config()
  File "/workspace/v-leiwang3/asplos-tvm/benchmark/utils.py", line 80, in load_config
    with open(config_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/v-leiwang3/asplos-tvm/benchmark/configs.json'
```

and I tried to provide a empty configs.json file, it didn't pass as well, any suggestions?

**Comment by Hzfengsy** [comment]
Sorry. `json` files are ignored by the `.gitignore`. I change the file name and update the code. 

Thanks for the error reporting.
